// examples/vite-vue/src/App.vue
<script setup lang="ts">
import { useSWR } from 'shiwas/vue'
const { data, error, isLoading, isValidating } = useSWR(
  "https://jsonplaceholder.typicode.com/posts/1",
  (url: any) => fetch(url).then(res => res.json())
);
console.log(data.value, error.value, isLoading.value, isValidating.value)
</script>

<template>
  <div v-if="isLoading">Loading...</div>
  <div v-else-if="error">Error: {{ error.message }}</div>
  <div v-else>
    {{ data }}
  </div>
</template>

<style scoped></style>

// examples/bun-react/src/App.tsx
import { APITester } from "./APITester";
import "./index.css";
import { useSWR } from "shiwas/react"
import logo from "./logo.svg";
import reactLogo from "./react.svg";

export function App() {
  const { data, error, isLoading } = useSWR(
    "https://jsonplaceholder.typicode.com/posts/1",
    (url: string) => fetch(url).then(res => res.json())
  );

  if (isLoading) return <div>Loading...</div>;
  if (error) return <div>Error: {error.message}</div>;

  return (
    <div className="max-w-7xl mx-auto p-8 text-center relative z-10">
      <div className="flex justify-center items-center gap-8 mb-8">
        <p>{data?.title}</p>
        <img
          src={logo}
          alt="Bun Logo"
          className="h-24 p-6 transition-all duration-300 hover:drop-shadow-[0_0_2em_#646cffaa] scale-120"
        />
        <img
          src={reactLogo}
          alt="React Logo"
          className="h-24 p-6 transition-all duration-300 hover:drop-shadow-[0_0_2em_#61dafbaa] animate-[spin_20s_linear_infinite]"
        />
      </div>

      <h1 className="text-5xl font-bold my-4 leading-tight">Bun + React</h1>
      <p>
        Edit <code className="bg-[#1a1a1a] px-2 py-1 rounded font-mono">src/App.tsx</code> and save to test HMR
      </p>
      <APITester />
    </div>
  );
}

export default App;
