// app/src/adapters/react/use-swr.tsx
import { useCallback, useRef, useDebugValue, useMemo, useEffect, useContext, createContext, ReactNode } from 'react'
import { useSyncExternalStore } from 'use-sync-external-store/shim'
import { createSWR } from '../../core'
import type { SWRConfig as SWRConfiguration, SWRResponse, Key, Fetcher, SWRFetcher, BareFetcher } from './types'

// Global SWR instance
const globalSWR = createSWR()

// React Context for configuration
const ConfigContext = createContext<Partial<SWRConfiguration<any, any>>>({})

/**
 * Enhanced useSWR hook that matches the SWR API
 */
export function useSWR<Data = any, Error = any>(
  key: Key | null,
  fetcher?: SWRFetcher<Data> | null,
  config?: Partial<SWRConfiguration<Data, Error>>
): SWRResponse<Data, Error> {
  // Get config from context and props
  const contextConfig = useContext(ConfigContext)
  const mergedConfig = useMemo(() => ({
    ...contextConfig,
    ...config
  }), [contextConfig, config])

  // Create a stable reference to the SWR instance with config
  const swrRef = useRef(globalSWR)
  
  // Update config if changed
  useEffect(() => {
    if (mergedConfig) {
      swrRef.current.updateConfig(mergedConfig as any)
    }
  }, [mergedConfig])

  // Normalize fetcher to handle different signatures
  const normalizedFetcher = useMemo(() => {
    if (!fetcher) return null
    
    // If it's already a core fetcher, use it as-is
    if (fetcher.length === 2) return fetcher as Fetcher<Data>
    
    // Convert bare fetcher to core fetcher
    return (key: Key, options: any) => {
      if (Array.isArray(key)) {
        return (fetcher as BareFetcher<Data>)(...key)
      }
      return (fetcher as BareFetcher<Data>)(key)
    }
  }, [fetcher])

  // Ref to always have the latest fetcher without triggering re-renders or re-subscriptions
  const fetcherRef = useRef(normalizedFetcher)
  useEffect(() => {
    fetcherRef.current = normalizedFetcher
  }, [normalizedFetcher])

  // Create a stable subscribe function
  const subscribe = useCallback((callback: () => void) => {
    if (!key || !fetcherRef.current) return () => {}
    
    return swrRef.current.subscribe(key, () => {
      callback()
    }, fetcherRef.current)
  }, [key]) // Only depend on key
  
  // Cache for the snapshot to avoid infinite loops with useSyncExternalStore
  const lastStateRef = useRef<any>(null)

  // Get current snapshot
  const getSnapshot = useCallback(() => {
    let nextState: any;
    
    if (!key || !fetcherRef.current) {
      nextState = { 
        data: mergedConfig?.fallbackData, 
        error: undefined, 
        isValidating: false, 
        isLoading: false 
      }
    } else {
      const entry = swrRef.current.get(key)
      const data = entry?.data ?? mergedConfig?.fallbackData
      
      nextState = {
        data,
        error: entry?.error,
        isValidating: entry?.isValidating || false,
        isLoading: entry?.isLoading || false
      }
    }

    // Return the cached state if it's deeply equal (or just shallowly equal for these properties)
    if (
      lastStateRef.current &&
      lastStateRef.current.data === nextState.data &&
      lastStateRef.current.error === nextState.error &&
      lastStateRef.current.isValidating === nextState.isValidating &&
      lastStateRef.current.isLoading === nextState.isLoading
    ) {
      return lastStateRef.current
    }

    lastStateRef.current = nextState
    return nextState
  }, [key, mergedConfig?.fallbackData]) // Only depend on key and fallbackData
  
  // Use sync external store for React 18+ compatibility
  const state = useSyncExternalStore(subscribe, getSnapshot, getSnapshot)
  
  // Create mutate function
  const mutate = useCallback(
    (data?: any, options?: any) => {
      if (!key) return Promise.resolve(undefined)
      return swrRef.current.mutate(key, data, options)
    },
    [key]
  )

  // Handle suspense mode
  if (mergedConfig?.suspense) {
    if (state.error) {
      throw state.error
    }
    if (state.data === undefined) {
      // In suspense mode, we need to trigger the fetch and throw a promise
      const promise = new Promise<Data>((resolve, reject) => {
        const unsubscribe = swrRef.current.subscribe(key, (data, error) => {
          if (error) {
            reject(error)
          } else if (data !== undefined) {
            resolve(data)
          }
        })
        
        // Start the fetch if not already loading
        const entry = swrRef.current.get(key)
        if (!entry?.isLoading && !entry?.isValidating) {
          swrRef.current.revalidate(key)
        }
        
        return unsubscribe
      })
      
      throw promise
    }
  }
  
  // Debug value for React DevTools
  useDebugValue(state.data ? `data: ${JSON.stringify(state.data)}` : 'loading')
  
  return {
    ...state,
    loading: state.isLoading,
    validating: state.isValidating,
    mutate
  }
}

/**
 * SWR configuration provider component
 */
export function SWRConfig<Data = any, Error = any>({
  children,
  value
}: {
  children: ReactNode
  value: Partial<SWRConfiguration<Data, Error>>
}) {
  return (
    <ConfigContext.Provider value={value}>
      {children}
    </ConfigContext.Provider>
  )
}

/**
 * Interface type for configuration
 */
export type SWRConfig<Data = any, Error = any> = SWRConfiguration<Data, Error>

/**
 * Hook for manual mutation
 */
export function useSWRMutate<Data = any, Error = any>() {
  return useCallback(
    (key: Key, data?: any, options?: any) => {
      return globalSWR.mutate(key, data, options)
    },
    []
  )
}

/**
 * Hook for accessing the global SWR instance
 */
export function useSWRInstance() {
  return globalSWR
}

/**
 * Hook for prefetching data
 */
export function useSWRPrefetch<Data = any, Error = any>() {
  return useCallback(
    (key: Key, fetcher: SWRFetcher<Data>) => {
      const normalizedFetcher = fetcher.length === 2 
        ? fetcher as Fetcher<Data>
        : (k: Key) => (fetcher as BareFetcher<Data>)(Array.isArray(k) ? k : [k])
      
      return globalSWR.revalidate(key, { dedupe: true })
    },
    []
  )
}

export default useSWR

// app/src/adapters/solid/use-swr.tsx
import { createSignal, createEffect, onCleanup, Suspense, Show, createContext, useContext, createMemo } from 'solid-js'
import { createSWR } from '../../core'
import type { SWRConfig as SWRConfiguration, SWRResponse, Key, Fetcher, SWRFetcher } from './types'

// Global SWR instance
const globalSWR = createSWR()

// Solid Context for configuration
const ConfigContext = createContext<Partial<SWRConfiguration<any, any>>>({})

/**
 * Enhanced useSWR hook for Solid
 */
export function useSWR<Data = any, Error = any>(
  key: Key | null,
  fetcher?: SWRFetcher<Data> | null,
  config?: Partial<SWRConfiguration<Data, Error>>
): SWRResponse<Data, Error> {
  // Get config from context and props
  const contextConfig = useContext(ConfigContext)
  const mergedConfig = createMemo(() => ({
    ...contextConfig,
    ...config
  }))

  // Create a stable reference to SWR instance with config
  const swrRef = createMemo(() => globalSWR)
  
  // Update config if changed
  createEffect(() => {
    if (mergedConfig) {
      swrRef().updateConfig(mergedConfig as any)
    }
  })

  // Normalize fetcher to handle different signatures
  const normalizedFetcher = createMemo(() => {
    if (!fetcher) return null
    
    // If it's already a core fetcher, use it as-is
    if (fetcher.length === 2) return fetcher
    
    // Convert bare fetcher to core fetcher
    return (k: Key, options: any) => {
      if (Array.isArray(k)) {
        return (fetcher as any)(...k)
      }
      return (fetcher as any)(k)
    }
  })

  // Create signals
  const [data, setData] = createSignal<Data | undefined>(
    key ? swrRef().get(key)?.data ?? mergedConfig()?.fallbackData : mergedConfig()?.fallbackData
  )
  const [error, setError] = createSignal<Error | undefined>(
    key ? swrRef().get(key)?.error : undefined
  )
  const [isLoading, setIsLoading] = createSignal<boolean>(
    key ? swrRef().get(key)?.isLoading ?? false : false
  )
  const [isValidating, setIsValidating] = createSignal<boolean>(
    key ? swrRef().get(key)?.isValidating ?? false : false
  )

  // Subscribe to SWR changes
  let unsubscribe: (() => void) | undefined

  createEffect(() => {
    if (!key || !normalizedFetcher()) return
    
    unsubscribe = swrRef().subscribe(key, (newData: any, newError: any, newIsValidating?: boolean, newIsLoading?: boolean) => {
      setData(newData)
      setError(newError)
      setIsValidating(newIsValidating ?? false)
      setIsLoading(newIsLoading ?? false)
    }, normalizedFetcher() as any)
    
    return unsubscribe
  })

  // Cleanup on destroy
  onCleanup(() => {
    unsubscribe?.()
  })

  // Create mutate function
  const mutate = createMemo(() => 
    (mutateData?: Data | Promise<Data> | ((currentData?: Data) => Data | Promise<Data>), options?: any) => {
      if (!key) return Promise.resolve(undefined)
      return swrRef().mutate(key, mutateData, options)
    }
  )

  // Handle suspense mode
  if ((mergedConfig as any)?.suspense) {
    if (error()) {
      throw error()
    }
    if (data() === undefined) {
      // In suspense mode, we need to trigger fetch and throw a promise
      const promise = new Promise<Data>((resolve, reject) => {
        const unsubscribe = swrRef().subscribe(key, (data: any, error: any) => {
          if (error) {
            reject(error)
          } else if (data !== undefined) {
            resolve(data)
          }
        })
        
        // Start the fetch if not already loading
        const entry = swrRef().get(key)
        if (!entry?.isLoading && !entry?.isValidating) {
          swrRef().revalidate(key)
        }
        
        return unsubscribe
      })
      
      throw promise
    }
  }

  return {
    get data() { return data() },
    get error() { return error() },
    get isLoading() { return isLoading() },
    get isValidating() { return isValidating() },
    get loading() { return isLoading() },
    get validating() { return isValidating() },
    mutate: mutate()
  }
}

/**
 * Solid configuration provider component
 */
export function SWRConfig<Data = any, Error = any>(props: {
  children: any
  value?: Partial<SWRConfiguration<Data, Error>>
}) {
  return (
    <ConfigContext.Provider value={props.value || {}}>
      {props.children}
    </ConfigContext.Provider>
  )
}

/**
 * Interface type for configuration
 */
export type SWRConfig<Data = any, Error = any> = SWRConfiguration<Data, Error>

/**
 * Hook for manual mutation
 */
export function useSWRMutate<Data = any, Error = any>() {
  return createMemo(() => 
    (key: Key, data?: Data | Promise<Data> | ((currentData?: Data) => Data | Promise<Data>), options?: any) => {
      return globalSWR.mutate(key, data, options)
    }
  )
}

/**
 * Hook for accessing global SWR instance
 */
export function useSWRInstance() {
  return globalSWR
}

/**
 * Hook for prefetching data
 */
export function useSWRPrefetch<Data = any, Error = any>() {
  return createMemo(() => 
    (key: Key, fetcher: Fetcher<Data>) => {
      const normalizedFetcher = fetcher.length === 2 
        ? fetcher
        : (k: Key) => (fetcher as any)(Array.isArray(k) ? k : [k])
      
      return globalSWR.revalidate(key, { dedupe: true })
    }
  )
}

export default useSWR
